/*
 * "What is this?" explanations. Any element with data-info="<key>" shows a card after the
 * pointer rests on it for 3 seconds (or a long press on touch screens), saying what the
 * figure or control represents and where the data comes from.
 */
(function (root) {
  'use strict';

  const APPS = 'Planning applications: City of Mississauga development applications (monthly layer, Growth Management active applications, site plan applications); City of Brampton Planning – Land Use – Development (OPA / ZBA / subdivision, site plan, condominium, draft plan of subdivision, pre-consultation); Town of Caledon development applications.';
  const PERMITS = 'Building permits: City of Mississauga issued building permits and Growth Management permits; City of Brampton building permits; Town of Caledon building permits (AMANDA). New-build permits only unless “New buildings only” is off.';
  const SNAPSHOT = 'Refreshed every Monday from the municipalities’ open-data ArcGIS services.';
  const PPU = 'Persons per unit: Region of Peel design criteria (single / semi 4.2, townhouse 3.4, apartment 2.7; editable under Breakdown & design criteria).';
  const CENSUS = 'Statistics Canada, 2021 and 2016 Censuses of Population: population and private dwellings by dissemination area (DA). For a secondary plan or MTSA, each DA counts by the share of its land inside the area.';

  const INFO = {
    'quick-views': { title: 'Quick views', body: 'One tap shows a single phase (or every phase not yet completed or withdrawn). The bar shows how the developments listed split across phases.', source: `${APPS} ${PERMITS}` },
    'phases': { title: 'Phases', body: 'Each development’s phase is the furthest stage reached by any of its files, read from the status text and milestone dates in the municipal data: inception (pre-consultation or submitted), under review, approved, permit issued, under construction (inspections), completed (occupancy, final inspection or permit closed), or withdrawn / refused.', source: `${APPS} ${PERMITS}` },
    'focus': { title: 'Focus', body: 'Narrows the developments further and combines with a phase. Growth: applications proposing new homes. Committed capacity: growth approved or permitted but not yet completed. Left to build: planned units with no building permit yet. Stalled: still in planning with no activity for 2 years.', source: `${APPS} ${PERMITS}` },
    'municipality': { title: 'Municipality', body: 'Shows developments in one local municipality of Peel Region.', source: 'Municipality of the source dataset each record comes from.' },
    'secondary-plans': { title: 'Secondary plans', body: 'Tick one or several plans to keep only developments whose location falls inside them. Mississauga plans by character area rather than secondary plans, so its Official Plan character areas are listed.', source: 'City of Brampton – Brampton Plan Schedule 10 Secondary Planning Areas; Town of Caledon – in-effect Secondary Plan Areas; City of Mississauga – Official Plan Character Areas. Rebuilt weekly.' },
    'mtsa': { title: 'Major Transit Station Areas', body: 'Keeps developments inside the chosen MTSA: the area around a transit station planned for higher density.', source: 'Region of Peel MTSA delineation as published by the City of Mississauga (2024); City of Brampton – Brampton Plan Schedules 1A / 1B primary and planned MTSAs. Rebuilt weekly.' },
    'record-type': { title: 'Record type', body: 'By default only developments with a planning application are shown, with the building permits that belong to them. “All records” adds permits with no planning application (infill houses, additions).', source: `${APPS} ${PERMITS}` },
    'units': { title: 'Units', body: 'Filters by dwelling units: growth (adds units) or a minimum number of units. Units on a development are counted once: the larger of the units planned on its applications and the units on its building permits.', source: `${APPS} ${PERMITS}` },
    'new-only': { title: 'New buildings only', body: 'Hides permits for alterations, signs, pools, decks, demolitions and similar work, keeping new buildings and permits that add units.', source: PERMITS },
    'timeline': { title: 'Timeline', body: 'Keeps developments with activity in the chosen years. The drop-down picks which milestone must fall in the range (submitted, approved, permit issued, completed, or any). Bars: developments per year.', source: 'Milestone dates in the municipal application and permit records.' },
    'projects-list': { title: 'On the map', body: 'Developments matching the filters that are inside the part of the map you are looking at; pan or zoom and the list follows. Sort by latest activity, units, units left to build or address. Files at the same address or on the same land (an application’s boundary) are combined into one development, so each is counted once.', source: `${APPS} ${PERMITS}` },
    'census': { title: 'Growth since the census', body: 'Starts from the census that fits the timeline (2021 Census for a timeline starting 2021 or later; 2016 Census for one starting earlier, as far back as the application data goes) and adds, in turn, homes completed since census day, homes approved but not yet built, and homes proposed on applications still in review — the full build-out of the planning applications. Applies to Peel or the selected municipality, secondary plans or MTSA; other filters are ignored.', source: `${CENSUS} ${PPU}` },
    'census-base': { title: 'Census baseline', body: 'Population and private dwellings counted on census day: 11 May 2021, or 10 May 2016 when the timeline starts before 2021.', source: CENSUS },
    'census-built': { title: '+ Built since', body: 'Adds units on building permits completed since 11 May 2021, converted to people at Peel persons-per-unit. Brampton and Caledon publish no completion date, so it is estimated as the issue date + 12 months (houses) or + 30 months (20+ units).', source: `${PERMITS} ${PPU}` },
    'census-approved': { title: '+ Approved, not yet built', body: 'Adds committed growth: units planned on planning applications that are approved or have a building permit, not yet completed.', source: `${APPS} ${PPU}` },
    'census-proposed': { title: '+ Proposed (full build-out)', body: 'Adds units on applications still in pre-consultation or review. With the layers before it, this is the full build-out of every planning application in the area.', source: `${APPS} ${PPU}` },
    'growth-bars': { title: 'Growth bars', body: 'Each bar runs from the 2021 baseline (grey) through built since (green), approved (blue) and proposed (hatched) to full build-out. Hover or tap a segment for its value.', source: `${CENSUS} ${APPS} ${PERMITS}` },
    'demand': { title: 'Population & servicing demand', body: 'Population, water and wastewater demand for the developments shown, using Region of Peel design criteria. The drop-down picks which units count: all, committed, left to build, not yet completed, or completed.', source: `${PPU} Water: 270 L/cap/d, max day ×1.8, peak hour ×3.0 (Peel Water and Wastewater Modelling Demand Table, Aug 2024). Wastewater: 290 L/cap/d with Harmon peaking limited to 2.0–4.0 (Peel Linear Wastewater Standards).` },
    'demand-units': { title: 'Dwelling units', body: 'Units counted for the developments shown, each development once (the larger of planned and permitted units).', source: `${APPS} ${PERMITS}` },
    'demand-pop': { title: 'Population', body: 'Units × persons per unit by dwelling type (from the unit mix where published, otherwise read from the development description).', source: PPU },
    'demand-water': { title: 'Water demand', body: 'Average day = population × 270 L/cap/d; maximum day ×1.8; peak hour ×3.0. Litres per second.', source: 'Region of Peel Water and Wastewater Modelling Demand Table (Aug 2024), from the 2020 DC Background Study.' },
    'demand-wastewater': { title: 'Wastewater flow', body: 'Average dry weather = population × 290 L/cap/d; dry weather peak = average × Harmon factor M = 1 + 14 / (4 + √P), P in thousands, kept between 2.0 and 4.0. I&I (infiltration and inflow) = 0.26 L/s per hectare of gross site area; peak wet weather = dry weather peak + I&I. Site area is the application boundary, or an estimate from the units where there is none. Residential only; employment flows are in the Employment tile.', source: 'Region of Peel Linear Wastewater Standards; site areas from the planning application boundaries.' },
    'ii': { title: 'I&I from growth', body: 'Infiltration and inflow from the development sites added since the 2021 Census: 0.26 L/s per hectare of gross site area, split between built, approved and proposed by each site’s share of units.', source: 'Region of Peel Linear Wastewater Standards; site areas from the planning application boundaries (estimated from units where there is none).' },
    'aerial': { title: 'Aerial check', body: 'Compares the site on the aerial photo from before the application with the latest photo, and building footprints traced from the photos, to estimate the chance the development is complete. An estimate for screening, not a site inspection.', source: 'City of Mississauga aerial imagery 2013–2024 and building footprints 2020–2024; City of Brampton orthophotos 2004–2025 and building footprints; Town of Caledon orthophotos 2014–2025.' },
    'buildout': { title: 'Units, jobs & build-out', body: 'Planned: units on the planning applications (resubmissions counted once; separate site plan or condo phases added up). Permitted: units on building permits on the land. Completed: units on closed or occupied permits. Left to build: planned minus permitted.', source: `${APPS} ${PERMITS}` },
    'demand-employment': { title: 'Employment demand', body: 'Jobs on the shown developments (estimated from the industrial, office, retail, hotel and institutional floor areas on the applications), counted by the development\'s phase. Water = jobs × 250 L/employee/day, max day ×1.4, peak hour ×3.0. Wastewater = jobs × 270 L/employee/day, peaked with Harmon on the employee count kept between 2 and 4, plus I&I (0.26 L/s/ha) on non-residential site boundaries.', source: 'Region of Peel Water & Wastewater Modelling Demand Table (Aug 2024) for ICI water; Peel Water & Wastewater Modelling Demand Table, Aug 2024 (non-residential wastewater). Jobs from floor space per worker.' },
    'demand-combined': { title: 'Total demand', body: 'Residential plus employment. Each is peaked on its own and the peaks are added, as in a functional servicing report; wastewater peak wet weather includes I&I on both.', source: 'Region of Peel water and wastewater design criteria.' },
    'project-demand': { title: 'Servicing demand (this development)', body: 'Population, jobs, water and wastewater for this development: total, already completed, and remaining. Residential and employment are shown separately, then added. Peaks are for this site alone.', source: `${PPU} Peel water and wastewater design criteria.` },
    'map-view': { title: 'Map views', body: 'Presets of the layers and style; each view remembers your changes. Planning: aerial photo, addresses, markers by phase. Water: street map, pressure zones shaded by max day growth, markers by servicing layer (built since the census, approved, proposed) sized by people + jobs, existing watermains from street zoom and the DC water works. Wastewater: drainage areas, sewer pipes coloured by load / full capacity, existing sanitary sewers and the DC wastewater works. DC: markers coloured by servicing timing against the 2026 DC program, all DC works; tap a DC main or facility for what it relieves and who relies on it, or open DC timing in Layers & style.', source: 'Your settings, kept in this browser.' },
    'map-color': { title: 'Marker colour', body: 'Phase of the development; servicing timing (construction year of the planned main it would connect to, 2026 DC draft); data quality (outside every area, assigned to the nearest, no units or floor area, site area estimated, complete); servicing layer as in the Water / Wastewater tables (existing before the census, built since, approved, proposed); or the plant its catchment drains to. A hollow ring marks a development outside the mapped areas, assigned to the nearest one.', source: 'Municipal records; traced catchments.' },
    'map-size': { title: 'Marker size', body: 'Same size, or by build-out people + jobs at Peel persons per unit and floor space per job. Clusters then show the total people + jobs inside and the ring splits it by colour.', source: 'Peel DC Background Study persons per unit; floor space per job (editable criteria).' },
    'map-capacity': { title: 'Capacity layer', body: 'Catchment flow growth: each catchment\'s own average dry weather flow at build-out over its census flow (new = no census population). Pumping station load: the station\'s whole upstream build-out peak wet weather flow (design flows, ≈ with I&I on the drainage area) as % of its firm capacity in the 2020 Master Plan (green < 80%, amber 80–100%, red > 100%). Sewer pipe capacity: every Region sanitary pipe of 300 mm or more coloured by its load as a share of full-flow capacity (Manning, n 0.013, on the published slope; 14,000 pipes, 98% with a slope). Load = the 2021 Census population upstream at peak dry weather, scaled to the plant’s 2025 measured flow in the capacity check, plus growth since the census at Peel design peak wet weather (each development joins the nearest of these pipes and is carried down the network; flow is shared at splits by capacity). Existing wet-weather I&I, surcharge, storage and relief sewers are not modelled: a screen for where to look. Pressure zone growth: max day at build-out over the census. The sewer network is drawn outlet to outlet down to the plants. Tap a catchment, station, zone or plant for what loads it. The year slider in the legend phases approved and proposed growth in as set in Horizon years (Wastewater → Plants).', source: 'Traced catchments; 2020 Water & Wastewater Master Plan Vol. 4 Table 6; Peel design criteria; census.' },
    'scenario': { title: 'Scenario', body: 'Every assumption behind the servicing figures in one place: wastewater capacity check (calibrated to 2025 plant flows) or design flows, water max day factor, the 70 ML/d G.E. Booth → Clarkson diversion, developments outside the mapped areas (nearest or left out), and whether criteria were edited. Shown on every tab, the map legend, exports and share links.', source: 'Region of Peel 2025 reports; Peel design criteria.' },
    'map-tools': { title: 'Map tools', body: 'Measure: tap points for the distance along them, then select every shown development within 250 m – 2 km of the last point (adds to the selection, like the lasso). Test a site: tap where a proposed development would be, enter units by type, jobs and site area, and get its servicing check — pressure zone, sewer path with pumping station load, and the plant’s uncommitted reserve; tick “Count it” to add it to the Water / Wastewater totals as proposed (or approved). Test sites are kept in this browser and can be dragged.', source: 'Peel design criteria; traced catchments; 2020 Master Plan.' },
    'dc-works': { title: 'Planned works (2026 DC capital maps)', body: 'Proposed (2027–2051) and approved (2026) water and wastewater works from the Region of Peel 2026 Development Charges capital maps — a draft not yet approved by Council. Mains carry their construction year, component and project numbers and diameter; where the component also appears in the 2020 DC Background Study its route description is shown. Facilities (plants, pumping stations, reservoirs, elevated tanks, wells, odour control) carry their environmental assessment, property, design and construction years. In a development: the planned main it would connect to (within 400 m), trunks and facilities on its sewer path and in its pressure zone, the plant capacity steps, and a timing flag when a committed development relies on a main not yet built. Developments outside the traced network are assigned through the planned main they would connect to (within 1 km) before the nearest-area rule. Read from the PDFs by position (a few metres) and by transcription of the facility boxes; schedules are reviewed annually.', source: 'Region of Peel, Water and Wastewater Development Charges capital maps 2026 (draft v2); 2020 DC Background Study (Watson & Associates).' },
    'existing-pipes': { title: 'Existing pipes', body: 'Watermains and sanitary sewers from the Region of Peel, storm sewers from the City of Mississauga, the City of Brampton and the Region, loaded live for the map area from street zoom (15+) and coloured by type; thicker lines are larger pipes, dashed are force mains. Tap a pipe for its diameter, material, install year and slope where published. The development panel lists the nearest existing main of each type to the development’s point (within 200 m) — a pointer to what is in the street, not the connection point. Caledon does not publish storm sewers. It also gives the age and risk of the sanitary sewers on the site’s path (first 3 km): the oldest pipe with its material, and any pipe the Region rates moderate risk (tap to see it).', source: 'Region of Peel open data (waterwastWater, storm_infrastructure); City of Mississauga StormSegment; City of Brampton Stormwater assets.' },
    'dc-needs': { title: 'DC needs: existing capacity against the DC program', body: 'For each existing piece of infrastructure a development relies on, how much room is left and whether the 2026 DC capital program relieves it in time. Wastewater: sanitary sewers on its path that reach 90% of full-pipe capacity by build-out (grouped by the DC main that runs along them — a twin or replacement — or by run), pumping stations against their firm capacity, and the plant against 90% of its rated capacity (the master plan expansion trigger). Water: the treatment system (South Peel plants, or the Caledon wells) at 90% of rated maximum day, storage from the 2020 Master Plan assessment, and the large mains crossing into its pressure zone level (rough: 1.5 m/s full pipe; water pumping station capacities are not published). Room after approved = capacity − (existing + built + approved development), in people at Peel design criteria and in units at the development’s persons per unit. Runs out = the year approved and proposed growth reach it, phased as in Horizon years. Red: needed before the DC project (or no DC project); green: DC project in time; grey: room to build-out. Tap a DC project for what it relieves and the developments relying on it; DC timing lists every constraint in the network. A screen, not a hydraulic model.', source: 'Region of Peel sanitary and water mains (open data); 2020 Water and Wastewater Master Plan (pumping stations, storage, 90% plant trigger); 2025 plant reports; 2026 DC capital maps (draft); Peel design criteria.' },
    'map-show': { title: 'Show as', body: 'Markers (clusters with a ring split by the marker colour; hover a cluster for its phase counts) or a heatmap of people + jobs at build-out across the shown developments. The heatmap hides the markers; switch back to tap a development.', source: 'The shown developments at Peel persons per unit and employment rates.' },
    'ground': { title: 'Ground elevation', body: 'Ground surface elevation at the development’s point and at its catchment’s outlet, with the fall (or rise) between them in a straight line — a hint for whether the site drains by gravity toward the outlet. Measure & ground profile (Tools) draws the ground along any line. Terrain tiles from the Canadian Digital Elevation Model and SRTM (about 7 m pixels): the ground surface, not pipe inverts.', source: 'AWS Terrain Tiles (Mapzen Terrarium; CDEM, SRTM), open data.' },
    'pipe-labels': { title: 'Size labels', body: 'Labels each existing pipe (and the sewer capacity layer’s pipes) with its diameter in mm, one label per small area of the screen, largest pipes first. Existing pipes show from street zoom.', source: 'Region of Peel and municipal GIS (live); data/sewers.json.' },
    'phase-basis': { title: 'How the phase was set', body: 'Each municipal file (pre-consultation, official plan / zoning / subdivision, site plan, condominium, building permit) has a published status. The app reads it into a phase: “in review / circulated / appeal” → under review; “approved / registered / by-law passed / draft approved / agreement” → approved; a planning file that is “closed” or “final” → approved (only building permits can show construction or completion); permits: issued → permit issued, inspections → under construction, final / occupancy / closed → completed; withdrawn / refused / expired → not counted. A pre-consultation counts as inception whatever its status. A dated milestone (approval date, issue date, final inspection) can move a file forward but never back. The site shows the furthest phase of any file that is not withdrawn, except that files submitted after an earlier build was completed start a new cycle. Because the furthest phase wins, an older approval can make a site look approved while a newer submission is still in review — Approvals by stage and the flags show when that happens. Other flags: a completed demolition permit (it moves the phase but is not the new building), a site held at under construction because planned units have no permit yet, and an appeal to the Ontario Land Tribunal (an approval under appeal is not final).', source: 'Municipal application and permit records (status and date fields as published).' },
    'watchlist': { title: 'Your watchlist', body: 'Developments you starred with ☆ Watch on their panel, those that changed phase or were added in the latest weekly update first. The ★ Watched focus (More filters) shows just them on the map. Kept in this browser.', source: 'Your choices; weekly phase checks.' },
    'saved-views': { title: 'Saved views', body: 'Save the current filters, map position, map view and layers under a name, and open it again later from this list. Kept in this browser; Share link gives the filters and map position as a link for someone else.', source: 'Your settings.' },
    'fire-storm': { title: 'Fire flow and stormwater', body: 'Fire flow: the Region’s hydrants within 150 m of the development’s point (in service only), the nearest, and the pressure zone they are recorded in (flagged when it differs from the mapped zone, or when hydrants in two zones are nearby), plus the nearest large (750 mm+) watermain within 1.5 km. Hydrant flow tests are not published, so this is coverage and zone, not available fire flow. Stormwater: the nearest stormwater management pond within 1 km (Brampton and Caledon publish ponds; Mississauga does not), with its design controls (quality, erosion, quantity / flood), risk grade or assumption status where published, and the watershed / subwatershed. All live from the Region / municipal GIS; whether a pond was sized for the site is in its SWM report.', source: 'Region of Peel HydrantsExport and waterwastWater (large watermains); City of Brampton Stormwater assets (ponds); Town of Caledon stormwater management ponds.' },
    'dev-brief': { title: 'Development brief', body: 'The development at a glance, for servicing review. Status: the phase, the file and dated event that set it, a stall flag (planning with no activity for 2+ years, with the likely cause) and any appeal or withdrawal in the status text. Latest decision: the most recent council or committee item with a decision — the verdict, the motion (shortened), the vote — plus the requirements on record across all its items (holding provision, servicing / allocation, stormwater, Region of Peel comments, draft plan conditions, agreements, Section 37…; infrastructure items highlighted) and the issues residents and members raised. Servicing: water max day and peak hour with the share of its pressure zone, wastewater peak dry / wet and the most loaded pumping station on its sewer path, and its share of the plant’s uncommitted reserve. Existing mains, fire flow and stormwater: live from the Region / municipal GIS (see their own help). Build-out: planned, permitted, completed and left. Header flags: appeal, stalled, a pumping station at or over firm capacity at build-out, or a plant over-committed or past the master plan’s 90% trigger. Every phrase in the decision summary is taken from the agenda / minutes text; open History for the full item.', source: 'Municipal application and permit records; council and committee agendas and minutes (eSCRIBE); Peel design criteria; 2020 Water & Wastewater Master Plan; Region of Peel 2025 plant reports.' },
    'dev-history': { title: 'History', body: 'One dated history for the development, newest first and grouped by year: phase changes (from the weekly check, with the file event that moved it), council and committee items (open one for the motion, requirements, concerns, reports, correspondence and minutes), dated events on the planning files, and building permits. Key events counts permits per year; All dated events lists each one. The progress bar above shows the earliest date each phase was reached.', source: 'Municipal application and permit records; weekly phase checks; council and committee agendas and minutes (eSCRIBE).' },
    'source-records': { title: 'Source records', body: 'Each municipal file combined into this development, grouped by type (official plan / zoning / subdivision, site plan, condominium, pre-consultation, building permits adding units, other permits). Open a group for its files, oldest first by date received, with every field as published.', source: `${APPS} ${PERMITS} ${SNAPSHOT}` },
    'demand-selection': { title: 'What the demand covers', body: 'The servicing demand follows the selection in the sidebar: the phase (or phase group) and the focus, plus any other filter shown here (municipality, secondary plan, MTSA, years, search). Each development counts all its units, except the Committed capacity focus (approved or permitted units not yet completed) and the Left to build focus (planned units with no building permit yet). Withdrawn developments never count. Tap Change to adjust the selection.', source: 'Your selection in the sidebar.' },
    'selection': { title: 'Selected area', body: 'Tap the select tool on the map (under the zoom buttons), then draw around developments with a finger or the mouse. The developments shown on the map inside the drawn area are added up: build-out by type, servicing demand (residential + employment, total / completed / remaining, peaked as one area) and growth since the 2021 Census. Draw more areas to add to the selection; remove single developments from the list.', source: 'The shown developments; 2021 Census dissemination areas whose centre falls inside the drawn area.' },
    'da-layer': { title: '2021 census areas', body: 'A light border around each census dissemination area (2021, or 2016 when the timeline starts before 2021), on by default (the smallest census geography, a few hundred to a few thousand people each). Hover or tap one for its 2021 population and dwellings. These are the areas behind the census baseline in Growth since 2021 and in a drawn selection.', source: 'Statistics Canada, 2021 Census of Population – dissemination areas (boundaries simplified to ~4 m).' },
    'unit-types': { title: 'Build-out by dwelling type', body: 'Planned, permitted, completed and left-to-build units split by type. Planned units use the unit mix published with the application where there is one, else the counts in the application description ("299 single detached, 217 townhouses…"), else the type read from the description. Permitted and completed units are typed from each building permit\'s own description; permits that don\'t say go to the types with room left in the plan. Stacked and back-to-back towns count as apartments, as for Peel persons-per-unit. Columns add up to the tiles above. Employment floor space has no unit-by-unit permits, so it moves with the development\'s phase.', source: 'Planning applications and building permits (Mississauga, Brampton, Caledon); employment from the application descriptions.' },
    'employment': { title: 'Employment', body: 'Non-residential uses named on the planning applications — industrial / logistics, office, retail / commercial, hotel, institutional — with the floor area stated in the description (or the floor-area field on a purely non-residential file), and estimated jobs at typical floor space per worker: industrial 110 m², office 25 m², retail 45 m², hotel 60 m², institutional 50 m² per job by default (editable under Breakdown &amp; criteria). An estimate; descriptions do not always state floor area.', source: 'Planning application descriptions and floor-area fields (Mississauga, Brampton, Caledon).' },
    'parent-app': { title: 'Part of planning application', body: 'The planning application(s) whose land contains this permit; the permit’s units count toward that application’s build-out, not on top of it.', source: APPS },
    'data-sources': { title: 'Data sources', body: 'Each layer read, its record count and when it was last refreshed. Untick a layer to leave it out.', source: SNAPSHOT },
    'duplicate-check': { title: 'Duplicate check', body: 'Evidence that each file and each unit is counted once: copies of the same file merged, integrity checks that must be zero, and a reconciliation from units on every record to units counted.', source: `${APPS} ${PERMITS}` },
    'legend': { title: 'Map legend', body: 'Marker colour and number show the development’s phase. Clusters show how many developments are grouped and their mix of phases.', source: `${APPS} ${PERMITS}` },

    // ---- One card per toggle ----
    'phase-all': { title: 'All phases', body: 'Every development whatever its phase, including withdrawn or refused files. Tap a single phase to see only that one.', source: `${APPS} ${PERMITS}` },
    'phase-active': { title: 'Active applications', body: 'The default view. Developments still moving: inception, under review, approved, permit issued or under construction. Leaves out completed and withdrawn / refused developments.', source: `${APPS} ${PERMITS}` },
    'phase-inception': { title: '1 · Inception', body: 'A pre-consultation is filed or an application has been received / submitted, but no review milestone is recorded yet. Read from status text such as “pre-consultation”, “received”, “submitted”, “open”, or a received / intake date on the file.', source: APPS },
    'phase-review': { title: '2 · Under review', body: 'The application is being processed: deemed complete, circulated, at a public meeting, statutory hearing, or under appeal (OLT / OMB). Read from status text and circulation / public-meeting / hearing dates.', source: APPS },
    'phase-approved': { title: '3 · Approved', body: 'Planning approval granted (official plan amendment, zoning by-law, draft plan of subdivision, site plan or condominium): approved, adopted, registered, enacted or a notice of decision, with no building permit issued yet.', source: APPS },
    'phase-permit': { title: '4 · Permit issued', body: 'A building permit has been issued on the development (including conditional / foundation permits), but no inspections are recorded yet.', source: PERMITS },
    'phase-construction': { title: '5 · Under construction', body: 'Building permit issued and inspections are underway, or construction has started. Also used when some permits are complete but planned units are still left to permit.', source: PERMITS },
    'phase-completed': { title: '✓ Completed', body: 'Built: occupancy granted, final inspection passed, or the permit is closed / completed, and no planned units are left without a permit. Brampton and Caledon publish no completion date, so completion is read from the permit status.', source: PERMITS },
    'phase-cancelled': { title: '× Withdrawn / refused', body: 'Every file on the development is withdrawn, refused, cancelled, revoked, denied or expired. These never count toward growth or servicing demand.', source: `${APPS} ${PERMITS}` },
    'focus-growth': { title: 'Growth', body: 'Projects whose planning applications propose new dwelling units (units counted from the applications, not from permits alone). On by default.', source: APPS },
    'focus-committed': { title: 'Committed capacity', body: 'Growth that is approved, permitted or under construction but not yet completed: the units the servicing system is already committed to. Servicing demand counts only those committed units.', source: `${APPS} ${PERMITS}` },
    'focus-left': { title: 'Left to build', body: 'Projects with planned units that have no building permit yet (planned minus permitted). Servicing demand counts only those units.', source: `${APPS} ${PERMITS}` },
    'focus-employment': { title: 'Employment', body: 'Applications naming industrial / logistics, office, retail / commercial, hotel or institutional uses, read from their type and description.', source: APPS },
    'focus-major': { title: 'Major (100+ units)', body: 'Projects with 100 or more dwelling units.', source: `${APPS} ${PERMITS}` },
    'focus-newapps': { title: 'New in last 12 months', body: 'Projects whose first file was received in the last 12 months.', source: APPS },
    'focus-stalled': { title: 'Stalled 2+ years', body: 'Projects still in planning (inception, review or approved, no building permit) with no recorded activity for at least 2 years. Open permits are not included because many have no inspection dates in the source data.', source: APPS },
    'focus-week': { title: 'Changed this week', body: 'Projects that are new, or moved to another phase, in the latest weekly update.', source: SNAPSHOT },
    'muni-all': { title: 'All of Peel', body: 'Mississauga, Brampton and Caledon together.', source: 'Municipality of the source dataset each record comes from.' },
    'muni-Mississauga': { title: 'Mississauga', body: 'Projects from the City of Mississauga’s development application and building permit layers.', source: 'City of Mississauga open data (ArcGIS).' },
    'muni-Brampton': { title: 'Brampton', body: 'Projects from the City of Brampton’s planning (development) and building permit layers.', source: 'City of Brampton open data (ArcGIS).' },
    'muni-Caledon': { title: 'Caledon', body: 'Projects from the Town of Caledon’s development application and building permit (AMANDA) layers.', source: 'Town of Caledon open data (ArcGIS).' },
    'tab-demand': { title: 'Growth & demand', body: 'Top: Population, jobs, water and wastewater for the developments selected in the sidebar (phase, focus and filters), or for the selected development’s census area.', source: `${PPU} Peel water and wastewater design criteria.` },
    'tab-growth': { title: 'Growth since the census', body: 'The census population and dwellings, then growth built since census day, approved and proposed. Census year follows the timeline; a selected development narrows it to its census area.', source: `${CENSUS} ${PPU}` },
    'tab-criteria': { title: 'Criteria & references', body: 'Units by dwelling type and phase, build-out by type, and the editable design criteria (persons per unit, water and wastewater rates, peaking, I&I, employment).', source: 'Region of Peel design criteria (editable).' },
    'opt-basemap': { title: 'Background', body: 'Latest city aerial photos (Mississauga, Brampton, Caledon) over Esri imagery, with or without road labels; Esri imagery only; or a plain street map. Aerials are drawn 40% transparent.', source: 'City and town aerial imagery services; Esri World Imagery; CARTO / OpenStreetMap.' },
    'opt-labels': { title: 'Labels', body: 'Text shown beside each development dot from zoom 14: address and phase, address only, file numbers, units, or none.', source: `${APPS} ${PERMITS}` },
    'opt-orient': { title: 'Orientation', body: 'Road grid turns the map 44° so Peel’s concession roads run straight up and across; North up is the usual map.', source: '' },
    'north': { title: 'North arrow', body: 'Points to true north. Tap to switch between the road-grid view and north up.', source: '' },
    'select-tool': { title: 'Select an area', body: 'Draw around developments to add up their build-out, servicing demand and growth. Middle-drag moves the map while drawing; Esc cancels.', source: 'The shown developments; census dissemination areas.' },
    'pressure-zone': { title: 'Water pressure zones', body: 'Region of Peel water pressure zones (24): the parts of the water system served at the same hydraulic grade. Each development is placed in the zone its location point falls in. Toggle the outlines in the map options, filter by zone under Where, and see water demand per zone in Breakdown & criteria.', source: 'Region of Peel open data – Water Pressure Zone (wastewater_infrastructure layer 6).' },
    'drainage-area': { title: 'Wastewater drainage areas', body: 'Developments outside every traced catchment (or pressure zone) are assigned to the nearest one within 5 km of its edge — the area greenfield lands would most likely connect to — and marked “nearest”; switch to Leave out in the Water / Wastewater tabs. Traced from the Region of Peel sanitary sewer network: each sewer is followed downstream (manhole to manhole, through pumping stations) to the treatment plant it reaches — Lakeview (G.E. Booth), Clarkson or Inglewood WRRF; the Malton area by Pearson airport drains to the City of Toronto. Areas are split at pumping stations and at major trunk junctions, and outlined from the sewers they contain. Small gaps in the published network are bridged to the nearest pipe. Not the 2020 Master Plan\'s own drainage-area polygons (not published as data): check against the Master Plan figures.', source: 'Region of Peel open data – Wastewater Main, Wastewater Pumping Station and Wastewater Resource Recovery Plant layers.' },
    'tab-water': { title: 'Water', body: 'Water demand by pressure zone, in numerical order: census baseline + built since + approved + proposed (in review) = build-out, residential plus jobs on development sites, with a stacked bar of the population. Maximum day per layer and peak hour at build-out, in ML/d. The max day factor can be switched between Peel design (×2.0) and the factor observed at the South Peel plants in 2025 (×1.40). Below: 2025 production reported by the Region (Arthur P. Kennedy and Lorne Park plants, Caledon well systems) beside the model. Click a zone to zoom to it.', source: 'Region of Peel pressure zones; Statistics Canada census; municipal applications and permits; Region of Peel 2025 Drinking Water in Peel Summary Report and system annual reports.' },
    'tab-ww': { title: 'Wastewater', body: 'Two views. Plants & capacity: each treatment plant’s capacity chart (existing, built, approved, proposed against rated capacity, with the uncommitted reserve), the comparison with its 2025 annual report and its inflow by growth layer. Catchments: flows building up along the traced sewers to G.E. Booth (Lakeview), Clarkson and Inglewood, local + upstream = census + built + approved + proposed, with peak dry, I&I and peak wet weather. Mode: Capacity check (calibrated to 2025 flows, the basis for capacity statements) or Design flows (Peel criteria, for sizing). Details: Engineering shows the Harmon factor and drainage areas.', source: 'Region of Peel 2025 wastewater annual reports; catchments traced from the Region’s sewer network; Statistics Canada census; municipal applications and permits.' },
    'tab-plants': { title: 'Plants', body: 'Each wastewater treatment plant beside its 2025 annual report: rated capacity, reported average and highest day, the model today and the calibration factor. Then each plant’s total inflow by layer (census, York Region and City of Toronto inflows, built since, approved, proposed = build-out): population and jobs, average dry, peak dry, I&I and peak wet weather in ML/d, and average as a % of rated capacity. The diversion switch moves the planned 70 ML/d from G.E. Booth to Clarkson (2027–2028) as a fixed transfer.', source: 'Region of Peel 2025 G.E. Booth, Clarkson and Inglewood annual reports and Wastewater Collection System report; catchments traced from the sewer network; Statistics Canada census; municipal applications and permits.' },
    'water-reports': { title: 'Reported 2025 production', body: 'Treated water produced in 2025 as reported by the Region: average day, maximum day and rated capacity for the Arthur P. Kennedy and Lorne Park plants (South Peel, lake-based) and the five Caledon groundwater systems, with per-person use and the max day ÷ average factor. Reported production includes water supplied to York Region and Halton, all employment and non-revenue water, so a residential model runs lower.', source: 'Region of Peel 2025 Drinking Water in Peel Summary Report (Tables 62–69), South Peel and Caledon system annual reports.' },
    'plant-capacity': { title: 'Plant capacity', body: 'Each plant’s average dry weather flow as a % of its rated (annual average) capacity, stacked: existing (census + external inflows), built since, approved, proposed. The line is 100% of rated capacity. The dashed box is the uncommitted reserve capacity (Ontario MECP Procedure D-5-1: rated − existing − committed), with its population equivalent at the plant’s flow per person today. Population at 100% = (rated − external inflows) ÷ flow per person. Use “Calibrated to 2025 flows” for the measured-flow basis D-5-1 calls for.', source: 'Region of Peel 2025 plant annual reports; MECP Procedure D-5-1; this tool’s catchments and growth layers.' },
    'servicing-check': { title: 'Servicing', body: 'The whole development’s water and wastewater flows at Peel design criteria (as in a functional servicing report), its pressure zone, the traced sewer path from its catchment down to the treatment plant with its share of the build-out flow at each outlet, and what it means for the plant’s uncommitted reserve capacity: built and approved developments are already in the existing / committed flow, proposed ones would draw on the reserve. Below it, demand by stage: total, completed and remaining.', source: 'Peel design criteria; catchments traced from the Region’s sewer network; Region of Peel 2025 plant reports.' },
    'horizon': { title: 'Horizon years', body: 'Each plant’s average dry weather flow as a % of rated capacity by year: today’s flow, approved growth added evenly over a set number of years, then proposed growth, plus optional further growth beyond today’s applications and the planned diversion from its start year. The table gives the year each plant reaches 80%, 90% and 100%. Change the years to test scenarios; they are kept in this browser.', source: 'This tool’s plant model (Capacity check or Design flows); Region of Peel 2025 plant reports.' },
    'forecast-2051': { title: 'Applications against the 2051 forecast', body: 'For each municipality: the population, units and jobs growth allocated to 2051 (Region of Peel Land Needs Assessment, draft municipal allocation) beside the growth already in the application pipeline since the census — built, approved and proposed — and how much is still to be planned for.', source: 'Region of Peel Land Needs Assessment Report Update, appendices pp. 5.2-109 and 5.2-119; municipal applications and permits.' },
    'status-why': { title: 'Why this status', body: 'The file and dated event behind the development’s current phase, signals read from the municipal status text (appeal to the Ontario Land Tribunal, inactive, lapsed, withdrawn, recirculated, public meeting held, endorsed by council, draft approved, registered), and a stall flag when a development still in planning has had no recorded activity for 2+ years, with the likely cause. Council and committee items that name the file numbers are listed when available. Status text says what happened; staff reports and minutes carry the reasons.', source: 'Municipal application and permit records; council and committee agendas and minutes (eSCRIBE).' },
    'council-items': { title: 'Council and committee', body: 'Agenda and minutes items from Mississauga, Brampton and Caledon planning committees, council and general committee since 2019 that name this development’s file numbers: the date and meeting, the kind of item (public meeting, recommendation or information report, by-law, correspondence), the outcome (carried, deferred, referred…), links to the reports and correspondence, and the minutes text with the discussion, motion and vote. Updated weekly.', source: 'eSCRIBE meeting portals of the City of Mississauga, City of Brampton and Town of Caledon.' },
    'plant-reports': { title: '2025 annual reports vs. the model', body: 'Rated capacity is the plant’s approved annual average flow. Model today = census + built since (residential + development jobs) + external inflows known to reach the plant. The calibration factor = (reported − external inflows) ÷ model today; it absorbs existing employment and institutional flow, dry-weather infiltration and anything not modelled.', source: 'Region of Peel 2025 G.E. Booth, Clarkson and Inglewood annual reports; Wastewater Collection System report (York and Toronto inflows).' },
    'references': { title: 'References', body: 'The Region of Peel 2025 wastewater annual reports and drinking water reports, read in full and used for the comparisons in the Water, Wastewater and Plants tabs. Previous years are available on request from Peel’s Water Quality and Compliance team.', source: 'peelregion.ca – Wastewater annual reports; Water quality reports.' },
  };

  const DELAY = 3000, TOUCH_DELAY = 650;
  let timer = null, current = null, pending = null, card = null, suppressClick = false;

  function ensureCard() {
    if (card) return card;
    card = document.createElement('div');
    card.className = 'info-card';
    card.setAttribute('role', 'tooltip');
    card.hidden = true;
    document.body.appendChild(card);
    return card;
  }
  const esc = s => String(s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  function show(el) {
    const info = INFO[el.dataset.info];
    if (!info) return;
    const c = ensureCard();
    c.innerHTML = `<strong>${esc(info.title)}</strong><p>${esc(info.body)}</p>${info.source ? `<p class="info-src"><span>Source:</span> ${esc(info.source)}</p>` : ''}`;
    c.hidden = false;
    const r = el.getBoundingClientRect(), w = Math.min(340, innerWidth - 24);
    c.style.width = `${w}px`;
    const left = Math.max(12, Math.min(innerWidth - w - 12, r.left));
    const h = c.offsetHeight;
    const below = r.bottom + 8 + h < innerHeight;
    c.style.left = `${left}px`;
    c.style.top = `${below ? r.bottom + 8 : Math.max(12, r.top - h - 8)}px`;
    current = el;
  }
  function hide() { clearTimeout(timer); timer = null; current = null; pending = null; if (card) card.hidden = true; }

  function attach() {
    document.addEventListener('pointerover', e => {
      if (e.pointerType === 'touch') return;
      const el = e.target.closest('[data-info]');
      if (!el || el === current || el === pending) return;
      hide();
      pending = el;
      timer = setTimeout(() => show(el), DELAY);
    });
    document.addEventListener('pointerout', e => {
      if (e.pointerType === 'touch') return;
      const el = e.target.closest('[data-info]');
      if (el && !el.contains(e.relatedTarget)) hide();
    });
    // Touch: press and hold.
    let startXY = null;
    document.addEventListener('pointerdown', e => {
      if (card && !card.hidden && !card.contains(e.target)) hide();
      if (e.pointerType !== 'touch') return;
      const el = e.target.closest('[data-info]');
      if (!el) return;
      startXY = [e.clientX, e.clientY];
      clearTimeout(timer);
      timer = setTimeout(() => { show(el); suppressClick = true; }, TOUCH_DELAY);
    });
    // A long press shows the card; don't let its release also tap the control underneath.
    document.addEventListener('click', e => { if (suppressClick) { suppressClick = false; e.preventDefault(); e.stopPropagation(); } }, true);
    document.addEventListener('pointermove', e => {
      if (e.pointerType === 'touch' && startXY && Math.hypot(e.clientX - startXY[0], e.clientY - startXY[1]) > 10) { clearTimeout(timer); startXY = null; }
    });
    document.addEventListener('pointerup', e => { if (e.pointerType === 'touch') { clearTimeout(timer); startXY = null; } });
    addEventListener('scroll', hide, true);
    addEventListener('keydown', e => { if (e.key === 'Escape') hide(); });
  }
  if (typeof document !== 'undefined') attach();

  root.PeelInfo = { INFO, show, hide };
})(typeof window !== 'undefined' ? window : globalThis);
